/* Generated by           cobc 3.2.0 */
/* Generated from         ex0201.cob */
/* Generated at            8月 23 2023 13:47:13 */
/* GnuCOBOL build date    Jul 28 2023 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -v -C ex0201.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"ex0201.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	" 8月 23 2023 13:47:13"
#define  COB_MODULE_DATE		20230823
#define  COB_MODULE_TIME		134713

/* Global variables */
#include "ex0201.c.h"

/* Function prototypes */

static int		EX0201 ();
static int		EX0201_ (const int);
static void		EX0201_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (EX0201 ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'EX0201' */

/* ENTRY 'EX0201' */

static int
EX0201 ()
{
  return EX0201_ (0);
}

static int
EX0201_ (const int entry)
{
  /* Program local variables */
  #include "ex0201.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 10        : Entry     EX0201                  : ex0201.cob */
  l_2:;

  /* Line: 10        : Paragraph RUN-START               : ex0201.cob */

  /* Line: 12        : ADD                : ex0201.cob */
  cob_add_int (&f_18, cob_get_numdisp (b_17, 8), 0);

  /* Line: 13        : DISPLAY            : ex0201.cob */
  cob_display (0, 1, 4, &c_1, &f_17, &c_2, &f_18);

  /* Line: 14        : ADD                : ex0201.cob */
  cob_decimal_set_field (d_0, &f_17);
  cob_decimal_set_field (d_1, &f_18);
  cob_decimal_add (d_0, d_1);
  cob_decimal_get_field (d_0, &f_19, 0);

  /* Line: 15        : DISPLAY            : ex0201.cob */
  cob_display (0, 1, 6, &c_1, &f_17, &c_2, &f_18, &c_3, &f_19);

  /* Line: 18        : SUBTRACT           : ex0201.cob */
  cob_sub_int (&f_18, cob_get_numdisp (b_17, 8), 0);

  /* Line: 19        : DISPLAY            : ex0201.cob */
  cob_display (0, 1, 4, &c_1, &f_17, &c_2, &f_18);

  /* Line: 20        : SUBTRACT           : ex0201.cob */
  cob_decimal_set_field (d_0, &f_18);
  cob_decimal_set_field (d_1, &f_17);
  cob_decimal_sub (d_0, d_1);
  cob_decimal_get_field (d_0, &f_19, 0);

  /* Line: 21        : DISPLAY            : ex0201.cob */
  cob_display (0, 1, 6, &c_1, &f_17, &c_2, &f_18, &c_3, &f_19);

  /* Line: 24        : MULTIPLY           : ex0201.cob */
  cob_mul (&f_18, &f_17, 0);

  /* Line: 25        : DISPLAY            : ex0201.cob */
  cob_display (0, 1, 4, &c_1, &f_17, &c_2, &f_18);

  /* Line: 26        : MULTIPLY           : ex0201.cob */
  cob_decimal_set_field (d_0, &f_17);
  cob_decimal_set_field (d_1, &f_18);
  cob_decimal_mul (d_0, d_1);
  cob_decimal_get_field (d_0, &f_19, 0);

  /* Line: 27        : DISPLAY            : ex0201.cob */
  cob_display (0, 1, 6, &c_1, &f_17, &c_2, &f_18, &c_3, &f_19);

  /* Line: 30        : DIVIDE             : ex0201.cob */
  cob_div (&f_18, &f_17, 0);

  /* Line: 31        : DISPLAY            : ex0201.cob */
  cob_display (0, 1, 4, &c_1, &f_17, &c_2, &f_18);

  /* Line: 32        : DIVIDE             : ex0201.cob */
  cob_decimal_set_field (d_0, &f_18);
  cob_decimal_set_field (d_1, &f_17);
  cob_decimal_div (d_0, d_1);
  cob_decimal_get_field (d_0, &f_19, 0);

  /* Line: 33        : DISPLAY            : ex0201.cob */
  cob_display (0, 1, 6, &c_1, &f_17, &c_2, &f_18, &c_3, &f_19);

  /* Line: 35        : DIVIDE             : ex0201.cob */
  cob_div_quotient (&f_18, &f_17, &f_19, 0);
  cob_div_remainder (&f_20, 0);

  /* Line: 36        : DISPLAY            : ex0201.cob */
  cob_display (0, 1, 8, &c_1, &f_17, &c_2, &f_18, &c_3, &f_19, &c_4, &f_20);

  /* Line: 38        : STOP RUN           : ex0201.cob */
  cob_stop_run (b_2);

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  EX0201_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field DATA1 */
  memcpy (b_17, "00000140", 8);

  /* initialize field DATA2 */
  memcpy (b_18, "00000240", 8);

  /* initialize field DATA3 */
  memset (b_19, (unsigned char)'0', 8);

  /* initialize field DATA4 */
  memset (b_20, (unsigned char)'0', 8);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'EX0201' */

/* Initialize module structure for EX0201 */
static void EX0201_module_init (cob_module *module)
{
  module->module_name = "EX0201";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())EX0201;
  module->module_cancel.funcptr = (void *(*)())EX0201_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

